remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Mart√≠n's Cinema]
description: [come and enjoy some fine arts]
show_downloads: true
google_analytics:
